DROP TABLE Player CASCADE; 
DROP TABLE TEAM CASCADE; 
DROP TABLE MATCH CASCADE; 
DROP TABLE playermatch CASCADE; 
DROP TABLE playerrating CASCADE; 
DROP TABLE teammatch CASCADE; 
DROP TABLE TeamRating CASCADE;
